### PR TITLE
feat(i18n): add german

### PR DESCRIPTION
**Pull request by escapedcat**
Proposal for German. For some things I'm not a 100% sure.  

Want to send tips to some friends who would prefer German I assume.

### CODE REVIEW

**Comment by rolznz** [comment]
@escapedcat thanks very much for the translations! we're hustling to get our submission for BOLT FUN done in time, but I'll merge this as soon as I can!

**Comment by escapedcat** [comment]
No worries, you focus on your goal! :)

**Comment by rolznz** [comment]
image
Thanks @escapedcat !

**Comment by escapedcat** [comment]
How about this?
image
Let me now if I should adjust something!

**Comment by rolznz** [comment]
A lot of the elements don't have translation support yet. I'll let you know as soon as we've added more! 🙏

**Comment by SteffenWOTSdk** [comment]
Proposal for bulk tips:

- An option to bulk change the "Anon" label for give-aways to something else
- Clickable "copy link" button next to the links in "View bulk links" function
- an "already copied" ticker next to that 

Reason for proposals: 
1. I would like the Anon label changed in bulk to for instance be "commenter" or "participant"
2. sometimes I can't tell where I've gotten to in the queue, when manually copying and pasting links to receipients one by one

image

image

**Comment by SteffenWOTSdk** [comment]
> How about this? image Let me now if I should adjust something!

I am getting a lot of people, who are already on lightning, that simply don't notice that there are other options than phone no.

They don't necessarily like having to give out their details when they are already bitcoiners, so I would suggest making this more visible - maybe throw a header above it in bold with "Alternatives methods of claiming" or something - or just make it bolder and larger for people to see.

**Comment by rolznz** [comment]
@SteffenWOTSdk you should be able to use the "Skip onboarding" mode for tipping them.

If you want to still show the onboarding, we're going to add a new "Lightning onboarding" feature which will only allow lightning login, and suggest wallets before the claim process. Would that work? Also, this would be better in a new issue I think.

**Comment by SteffenWOTSdk** [comment]
The problem is, when doing a giveaway of say 100 x 100 sats, I have no idea if the person is or isn't onboarded, so that would add a step of me asking if they need the onboarding or not. The recipient could be a person getting their VERY first sats, or a hardcore stacker, and I won't know, unless I ask, and I can't ask 100 ppl if they are already on LN or not. 

So that "Lightning onboarding/Already on LN" added option would be the solution for me in my case.

I want to be able to ALWAYS just use LightSats in the same way, no matter who I am sending links to, or it will start being too extensive of an experience for me to tip/gift sats vs. onboarding... The beauty of LightSats is that I can send it to whoever, no matter if I am tipping or OP'ing. If that makes sense?

Will open a new issue on this, quoted from this comment, so no need to respond here.

**Pull request merged**
