### PR TITLE
feat: Add slovenian locale

### PR DESCRIPTION
**Pull request by hisenb3rg**
I've added all slovenian translations.

Will have another pass through later today and also test it with on a local app.

Would be great if we can get it merged in before the holidays :)

### CODE REVIEW

**Comment by rolznz** [comment]
Hi @hisenb3rg thanks for the PR! looks good to me, I can merge it and we can test it on the dev site (https://lightsats.fly.dev/)

Please ping me again when you have done your final changes

**Comment by hisenb3rg** [comment]
Hi @rolznz, thanks for quick reply!

I've made final updates and would be happy to have another look once deployed to dev!

**Comment by rolznz** [comment]
@hisenb3rg looks good to me, let me know if you want to make any changes before I push it to production

**Comment by hisenb3rg** [comment]
@rolznz I've made some final changes after testing it, you can push to prod after merging #202 :)

**Pull request merged**
