### PR TITLE
Add NL (Dutch) language support

### PR DESCRIPTION
**Pull request by Wenze**
Translated ‘tip’ in a way that it can be used for both ‘tip’ and ‘present’ by using the word ‘gift’. I’ve used Lightsats most of the times as birthday present, and then ‘tip’ is incorrect.

In 'items.json':
- Are "nonCustodial" and "custodial" used in the application? 
- Can these be short sentences, as the exact translation 'niet custodiaal' won't mean anything to a common person?

### CODE REVIEW

**Comment by rolznz** [comment]
@Wenze thanks very much for the translations!

> Are "nonCustodial" and "custodial" used in the application?
I think they are no longer shown. We used to show which wallets are custodial and non-custodial, but we have simplified the interface and instead order the wallets based on a number of factors (this being one of them). So no need to translate this.

**Comment by rolznz** [comment]
@Wenze you will be able to test the translations at https://lightsats.fly.dev/ (our dev site) once the github action has finished running.

**Comment by Wenze** [comment]
@rolznz I ran the user workflow and everything looks good. 

The only open question is the one I had in the initial pull request. I didn’t see the string “nonCustodial” so it doesn’t seem to be used. Therefore this can be pushed to production from my side.

**Comment by rolznz** [comment]
@Wenze I replied regarding that above but the formatting was a bit broken. 

I think custodial/non-custodial are no longer shown. We used to show which wallets are custodial and non-custodial, but we have simplified the interface and instead order the wallets based on a number of factors (this being one of them). So no need to translate this.

**Comment by Wenze** [comment]
> @Wenze I replied regarding that above but the formatting was a bit broken.
> 
> I think custodial/non-custodial are no longer shown. We used to show which wallets are custodial and non-custodial, but we have simplified the interface and instead order the wallets based on a number of factors (this being one of them). So no need to translate this.

All clear, thanks.

**Pull request merged**
